### ISSUE TITLE
Comments may cause parsing failure

### ISSUE THREAD

**Issue by muelli** [Bogdanp/elm-ast#92] opened 2017-12-10 20:48 UTC
I'm coming from https://github.com/dillonkearns/elm-typescript-interop/issues/3 and it seems that the elm-ast package fails to parse

```
port module Main exposing (..)


init location =
    let
        currentRoute =
            Routing.parseLocation location
    in
        --( initialModel currentRoute, fetchUser )
        ( initialModel currentRoute, Cmd.batch
                                            [ check "yo"
                                            , fetchUser
                                            ]  )
```

with

```
Err ((),{ data = "port module Main exposing (..)\n\n\ninit location =\n let\n currentRoute =\n Routing.parseLocation location\n in\n --( initialModel currentRoute, fetchUser )\n ( initialModel currentRoute, Cmd.batch\n [ check \"yo\"\n , fetchUser\n ] )\n\n", input = "init location =\n let\n currentRoute =\n Routing.parseLocation location\n in\n --( initialModel currentRoute, fetchUser )\n ( initialModel currentRoute, Cmd.batch\n [ check \"yo\"\n , fetchUser\n ] )\n\n", position = 33 },["expected end of input"])
```

**Comment by wende** [comment] 2017-12-10 21:41
Duplicate of #41

**Closed as completed by wende** 2017-12-10 21:41 UTC
