### ISSUE TITLE
Function type declaration in let expression

### ISSUE THREAD

**Issue by tunguski** [Bogdanp/elm-ast#77] opened 2017-07-16 21:25 UTC
Removing `hasImport : List String -> Bool` helps, yet this is valid elm code:

```elm
compile name =
    let
        hasImport : List String -> Bool
        hasImport name = True
    in
      hasImport name
```

**Comment by wende** [comment] 2017-07-16 22:01
Duplicate of #62 

Actually that should be quite easy to fix, but it'd require yet another Major version bump.
In elchemy I omit them with an ugly Regexp:
```
Regex.replace All (regex "\n +\\w+ : .*") (always "")
```

**Closed as completed** 2017-07-16 22:01 UTC
Labels: duplicate
